apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          ports:
            - containerPort: {{ .Values.elasticsearch.service.httpPort }}
            - containerPort: {{ .Values.elasticsearch.service.transportPort }}
          env:
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: discovery.type
              value: "single-node"
            - name: bootstrap.memory_lock
              value: "true"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              memory: {{ .Values.elasticsearch.resources.requests.memory }}
              cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.elasticsearch.volumes.data.size }}
