apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: mongo
spec:
  ports:
    - port: {{ .Values.mongo.service.port }}
      name: mongo
  clusterIP: None
  selector:
    app: mongo