{{- if .Values.efk.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix }}efk-stack
  namespace: argocd
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: https://argadepp.github.io/helm-chart
    targetRevision: 0.1.0
    chart: efk-chart
    helm:
      values: |
        ## Minimal Helm values ##
        kibana:
          ingress:
            enabled: true
            host: kibana.localhost
  destination:
    server: {{ .Values.global.clusterEndPoint }}
    namespace: {{ .Values.global.destNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true    
      - "ServerSideApply=true"        
{{- end }}      