{{- if .Values.grafanaOperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix }}grafana-operator
  namespace: argocd
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: {{ .Values.grafanaOperator.repoURL }}
    targetRevision: {{ .Values.grafanaOperator.targetRevision }}
    chart: {{ .Values.grafanaOperator.chart }}
    helm:
      values: |
        ## Minimal Helm values ##
        global:
        operator:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/grafana-operator
            tag: {{ .Values.grafanaOperator.operatorImageTag }}
            digest: ""
        grafana:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/grafana
            tag: {{ .Values.grafanaOperator.grafanaImageTag }}
            digest: ""
          ingress:
            enabled: true
            ingressClassName: "nginx"
            host: {{ .Values.grafanaOperator.ingressHost }}
            path: /
          persistence:
            enabled: true
            size: {{ .Values.grafanaOperator.persistenceSize }}
  destination:
    server: {{ .Values.global.clusterEndPoint }}
    namespace: {{ .Values.global.destNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"
{{- end }}
