{{- if .Values.loki.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix }}loki-stack
  namespace: argocd
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2  # Specify the version of the grafana-operator chart
    chart: loki-stack
    helm:
      values: |
        test_pod:
          enabled: false
          image: bats/bats:1.8.2
          pullPolicy: IfNotPresent
        loki:
          enabled: true
          isDefault: true       
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          datasource:
            jsonData: "{}"
            uid: ""  
        promtail:
          enabled: false          
  
        fluent-bit:
          enabled: false    
  destination:
    server: {{ .Values.global.clusterEndPoint }}
    namespace: {{ .Values.global.destNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"          
{{- end }}
