{{- if .Values.prom.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix }}prometheus-stack
  namespace: argocd
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.41.2  # Specify the version of kube-prometheus-stack
    chart: prometheus
    helm:
      values: |
        ## Minimal Helm values ##
        server:
          ingress:
            enabled: true
            hosts:
              - prometheus.localhost
            pathType: ImplementationSpecific
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/rewrite-target: /   
  destination:
    server: {{ .Values.global.clusterEndPoint }}
    namespace: {{ .Values.global.destNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true    
      - "ServerSideApply=true"        
{{- end }}      