{{- range .Values.datasources }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ $.Values.global.namePrefix }}{{ .name }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Values.global.grafanaInstance }}
  datasource:
    name: {{ .name }}
    type: {{ .type }}
    access: {{ .access }}
    url: {{ .url }}
    jsonData:
      "tlsSkipVerify": false
      "timeInterval": "5s"
      {{- range $key, $value := .jsonData }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
{{- end }}
