{{- if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ing
spec:
  tls:
  - hosts:
    - example.com
    secretName: example-com-tls
  rules:
  - host: {{ .Values.kibana.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: kibana
            port:
              number: 8080
        path: /
        pathType: Prefix
{{- end }}