{{- range $namespace := .Values.rbac.namespaces }}
{{- range $role := $namespace.roles }}
{{- if eq $role.type "admin" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ $namespace.name }}-admin-clusterrole"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}
{{- end }}
{{- end }}
