{{- range $namespace := .Values.rbac.namespaces }}
{{- range $role := $namespace.roles }}
{{- range $sa := $role.serviceAccounts }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ $sa }}-admin-clusterbinding"
subjects:
  - kind: ServiceAccount
    name: "{{ $sa }}"
    namespace: "{{ $namespace.name }}"
roleRef:
  kind: ClusterRole
  name: "{{ $namespace.name }}-admin-clusterrole"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
