
global:
  destNamespace: utilities
  clusterEndPoint: https://kubernetes.default.svc
  project: default


namePrefix: std-practice-
grafanaOperator:
  enabled: true
  repoURL: https://charts.bitnami.com/bitnami
  targetRevision: 4.7.2
  chart: grafana-operator
  operatorImageTag: 5.13.0-debian-12-r0
  grafanaImageTag: 11.2.0-debian-12-r3
  ingressHost: grafana.localhost
  persistenceSize: 1Gi

grafanaMimir:
  enabled: true
  repoURL: https://grafana.github.io/helm-charts
  targetRevision: 5.5.0 
  chart: mimir-distributed

loki:
  enabled: true
  
prom: 
  enabled: true    
  ingressHost: prom.localhost
cloudwatch:
  enabled: true  

efk:
  enabled: true